name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C++ sources.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '16'

  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install meson ninja
      - run: meson setup builddir/
        env:
          CC: gcc
      - run: pip install numpy
      - run: meson test -C builddir/ -v
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Linux_Meson_Testlog
          path: tests/builddir/meson-logs/testlog.txt



